###
POST http://localhost:8080/evaluate
Content-Type: application/json

{
    "exp": {
        "a":"b+c",
        "b":"23423",
        "c":"234",
        "d":"a-34/c",
        "e":"d+324*c",
        "G":"a+e"
    },
    "config": {
      "j":3
    }
}